services:
  os2borgerpc-admin:
    image: ghcr.io/os2borgerpc/os2borgerpc-admin-site:<specific-tag>
    environment:
      DB_HOST: db
      DB_NAME: bpc
      DB_USER: bpc
      DB_PASSWORD: bpc
      DB_PORT: ""
      ALLOWED_HOSTS: "*"
      CORE_SCRIPT_COMMIT_HASH: db319672efdcc0f7402c4a7370aa763be9960c38
      CORE_SCRIPT_VERSION_TAG: v0.1.4
      PC_IMAGE_RELEASES_URL: https://github.com/OS2borgerPC/os2borgerpc-image/releases
      KIOSK_IMAGE_RELEASES_URL: https://github.com/OS2borgerPC/os2borgerpc-kiosk-image/releases
      DEBUG: True
      SECRET_KEY: v3rys1kr3t
      # Admin contact - fill in your own name and email as desired.
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: os2borgerpc_admin@os2borgerpc-vendor.example
      ADMIN_PASSWORD: admin
      # Timezone/Language
      TIME_ZONE: Europe/Copenhagen
      LANGUAGE_CODE: da-dk

      INITIALIZE_DATABASE: True

      LOG_LEVEL: INFO

      # IF USING THE CICERO INTEGRATION
      CICERO_URL: CICERO_SERVER_HERE
      # This particular line makes it both skip the connection to the Cicero server AND the validation of the username/password
      # For that reason, depending on what you're testing, you might want to comment out this line
      CITIZEN_LOGIN_API_VALIDATOR: system.utils.always_validate_citizen
volumes:
  admin-media:/media